### ISSUE TITLE
请问您的博客是基于什么项目或者静态博客做的？

### ISSUE THREAD

**Issue by itfanr** [MorvanZhou/morvanzhou.github.io#1]
感觉风格很好。想学习一下。
谢谢！

**Comment by MorvanZhou** [comment]
Hi @itfanr ,
这个是 github 提供的 pages, https://pages.github.com/ , 用到的是 jekyll 编写的静态 blog. 我的website 是自己写的. 不过你可以用他们提供的很多模板.
